version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 8000:8000
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
    networks:
      - custom

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000

  db:
    image: postgres:16.1
    hostname: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=wasdbook
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_DB=wasdbook
      - POSTGRES_HOST=db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - custom

secrets:
   db_password:
     file: db_password.txt

volumes:
  postgres_data:

networks:
  custom:
    driver: bridge
