version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 8000:8000
    volumes:
      - ./services/backend:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    working_dir: '/app/src'
    depends_on:
      - db
  
  migration:
    build: ./services/backend
    volumes:
      - ./services/backend:/app
    command: /bin/bash -c "/app/alembic-entrypoint.sh"
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000

  db:
    image: postgres:16.1
    hostname: db
    expose:
      - 6432
    ports:
      - 6432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

secrets:
   db_password:
     file: db_password.txt

volumes:
  postgres_data:
